# Generated by Django 3.0.3 on 2020-10-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
